type KanjiDataType = {
  char: string;
  meaning: string;
  onyomi: string[];
  kunyomi: string[];
  jlpt: number;
}[];

export const KanjiData: KanjiDataType = [
  {
    char: "人",
    meaning: "Man, Human, Person, Character",
    onyomi: ["ジン", "ニン", "-と"],
    kunyomi: ["ひと", "-り"],
    jlpt: 5,
  },
  {
    char: "一",
    meaning: "One",
    onyomi: ["イチ", "イツ"],
    kunyomi: ["ひと.つ", "ひと-"],
    jlpt: 5,
  },
  {
    char: "日",
    meaning: "Sun, Day",
    onyomi: ["ニチ", "ジツ"],
    kunyomi: ["ひ", "-か"],
    jlpt: 5,
  },
  {
    char: "大",
    meaning: "Large, Many, Very",
    onyomi: ["ダイ", "タイ"],
    kunyomi: ["おお.きい", "おお.いに", "おお-"],
    jlpt: 5,
  },
  {
    char: "年",
    meaning: "Year",
    onyomi: ["ネン"],
    kunyomi: ["とし"],
    jlpt: 5,
  },
  {
    char: "出",
    meaning: "Appear, Go out",
    onyomi: ["シュツ", "スイ"],
    kunyomi: ["だ.す", "で.る"],
    jlpt: 5,
  },
  {
    char: "本",
    meaning: "Book",
    onyomi: ["ホン"],
    kunyomi: ["もと"],
    jlpt: 5,
  },
  {
    char: "中",
    meaning: "Middle",
    onyomi: ["チュウ", "ジュウ"],
    kunyomi: ["なか"],
    jlpt: 5,
  },
  {
    char: "子",
    meaning: "Child",
    onyomi: ["シ", "ス"],
    kunyomi: ["こ"],
    jlpt: 5,
  },
  {
    char: "見",
    meaning: "See, Idea, Opinion",
    onyomi: ["ケン"],
    kunyomi: ["み.る", "み.える", "み.せる"],
    jlpt: 5,
  },
  {
    char: "国",
    meaning: "Country",
    onyomi: ["コク"],
    kunyomi: ["くに"],
    jlpt: 5,
  },
  {
    char: "上",
    meaning: "Up, Top, Rise",
    onyomi: ["ジョウ", "ショウ"],
    kunyomi: [
      "うえ",
      "うわ-",
      "あ.げる",
      "あ.がる",
      "かみ",
      "の.ぼる",
      "のぼ.せる",
      "のぼ.す",
    ],
    jlpt: 5,
  },
  {
    char: "分",
    meaning: "Divide",
    onyomi: ["ブン", "ブ", "フン"],
    kunyomi: ["わ.ける", "わ.かる", "わ.かれる", "わ.かつ"],
    jlpt: 5,
  },
  {
    char: "生",
    meaning: "Life",
    onyomi: ["セイ", "ショウ"],
    kunyomi: [
      "なま",
      "い.かす",
      "い.きる",
      "い.ける",
      "う.まれる",
      "う.む",
      "き",
      "お.う",
      "は.える",
      "は.やす",
    ],
    jlpt: 5,
  },
  {
    char: "行",
    meaning: "To go",
    onyomi: ["コウ", "ギョウ", "アン"],
    kunyomi: ["ゆ.く", "い.く", "おこな.う"],
    jlpt: 5,
  },
  {
    char: "二",
    meaning: "Two",
    onyomi: ["ニ"],
    kunyomi: ["ふた.つ", "ふた"],
    jlpt: 5,
  },
  {
    char: "間",
    meaning: "Interval, Space, Between",
    onyomi: ["カン", "ケン"],
    kunyomi: ["あいだ", "ま"],
    jlpt: 5,
  },
  {
    char: "時",
    meaning: "Time",
    onyomi: ["ジ"],
    kunyomi: ["とき"],
    jlpt: 5,
  },
  {
    char: "気",
    meaning: "Spirit, Mind, Air",
    onyomi: ["キ", "ケ"],
    kunyomi: ["いき"],
    jlpt: 5,
  },
  {
    char: "十",
    meaning: "Ten",
    onyomi: ["ジュウ", "ジッ"],
    kunyomi: ["と", "とお"],
    jlpt: 5,
  },
  {
    char: "女",
    meaning: "Woman, Female",
    onyomi: ["ジョ", "ニョ", "ニョウ"],
    kunyomi: ["おんな", "め"],
    jlpt: 5,
  },
  {
    char: "三",
    meaning: "Three",
    onyomi: ["サン"],
    kunyomi: ["み", "みっ.つ"],
    jlpt: 5,
  },
  {
    char: "前",
    meaning: "Before",
    onyomi: ["ゼン"],
    kunyomi: ["まえ"],
    jlpt: 5,
  },
  {
    char: "入",
    meaning: "Enter",
    onyomi: ["ニュウ"],
    kunyomi: ["い.る", "はい.る", "い.れる"],
    jlpt: 5,
  },
  {
    char: "小",
    meaning: "Small",
    onyomi: ["ショウ"],
    kunyomi: ["こ- ", "お-", "ちい.さい"],
    jlpt: 5,
  },
  {
    char: "後",
    meaning: "After",
    onyomi: ["ゴ", "コウ"],
    kunyomi: ["のち", "あと", "うし.ろ", "おく.れる"],
    jlpt: 5,
  },
  {
    char: "長",
    meaning: "Long",
    onyomi: ["チョウ"],
    kunyomi: ["なが.い"],
    jlpt: 5,
  },
  {
    char: "下",
    meaning: "Below",
    onyomi: ["カ", "ゲ"],
    kunyomi: [
      "した",
      "しも",
      "もと",
      "さ.げる",
      "さ.がる",
      "くだ.る",
      "くだ.す",
      "くだ.さる",
      "お.ろす",
      "お.りる",
    ],
    jlpt: 5,
  },
  {
    char: "学",
    meaning: "Learn",
    onyomi: ["ガク"],
    kunyomi: ["まな.ぶ"],
    jlpt: 5,
  },
  {
    char: "月",
    meaning: "Month, Moon",
    onyomi: ["ガツ", "ゲツ"],
    kunyomi: ["つき"],
    jlpt: 5,
  },
  {
    char: "何",
    meaning: "What",
    onyomi: ["カ"],
    kunyomi: ["なに", "なん"],
    jlpt: 5,
  },
  {
    char: "来",
    meaning: "Come",
    onyomi: ["ライ"],
    kunyomi: ["くる", "きた.る", "きた.す"],
    jlpt: 5,
  },
  {
    char: "話",
    meaning: "Talk",
    onyomi: ["ワ"],
    kunyomi: ["はなす", "はなし"],
    jlpt: 5,
  },
  {
    char: "山",
    meaning: "Mountain",
    onyomi: ["サン"],
    kunyomi: ["やま"],
    jlpt: 5,
  },
  {
    char: "高",
    meaning: "Expensive, High",
    onyomi: ["コウ"],
    kunyomi: ["たか", "たか.い", "たか.まる", "たか.める"],
    jlpt: 5,
  },
  {
    char: "今",
    meaning: "Now",
    onyomi: ["コン", "キン"],
    kunyomi: ["いま"],
    jlpt: 5,
  },
  {
    char: "書",
    meaning: "Write",
    onyomi: ["ショ"],
    kunyomi: ["か.く"],
    jlpt: 5,
  },
  {
    char: "五",
    meaning: "Five",
    onyomi: ["ゴ"],
    kunyomi: ["いつ-", "いつ.つ"],
    jlpt: 5,
  },
  {
    char: "名",
    meaning: "Name",
    onyomi: ["メイ", "ミョウ"],
    kunyomi: ["な"],
    jlpt: 5,
  },
  {
    char: "金",
    meaning: "Gold",
    onyomi: ["キン", "コン"],
    kunyomi: ["かね"],
    jlpt: 5,
  },
  {
    char: "男",
    meaning: "Male",
    onyomi: ["ダン", "ナン"],
    kunyomi: ["おとこ"],
    jlpt: 5,
  },
  {
    char: "外",
    meaning: "Outside",
    onyomi: ["ガイ", "ゲ"],
    kunyomi: ["そと", "ほか", "は.ずす", "はず.れる"],
    jlpt: 5,
  },
  {
    char: "四",
    meaning: "Four",
    onyomi: ["シ"],
    kunyomi: ["よ", "よ.つ", "よっ.つ", "よん"],
    jlpt: 5,
  },
  {
    char: "先",
    meaning: "Ahead",
    onyomi: ["セン"],
    kunyomi: ["さき"],
    jlpt: 5,
  },
  {
    char: "川",
    meaning: "River",
    onyomi: ["セン"],
    kunyomi: ["かわ"],
    jlpt: 5,
  },
  {
    char: "東",
    meaning: "East",
    onyomi: ["トウ"],
    kunyomi: ["ひがし"],
    jlpt: 5,
  },
  {
    char: "聞",
    meaning: "Listen",
    onyomi: ["ブン", "モン"],
    kunyomi: ["き.く", "き.こえる"],
    jlpt: 5,
  },
  {
    char: "語",
    meaning: "Talk",
    onyomi: ["ゴ"],
    kunyomi: ["かた.る", "かた.らう"],
    jlpt: 5,
  },
  {
    char: "九",
    meaning: "Nine",
    onyomi: ["ク", "キュウ"],
    kunyomi: ["ここの.つ"],
    jlpt: 5,
  },
  {
    char: "食",
    meaning: "Food, Eat",
    onyomi: ["ショク", "ジキ"],
    kunyomi: ["た.べる", "く.う"],
    jlpt: 5,
  },
  {
    char: "八",
    meaning: "Eight",
    onyomi: ["ハチ"],
    kunyomi: ["や", "や.つ", "よう"],
    jlpt: 5,
  },
  {
    char: "水",
    meaning: "Water",
    onyomi: ["スイ"],
    kunyomi: ["みず"],
    jlpt: 5,
  },
  {
    char: "天",
    meaning: "Heaven",
    onyomi: ["テン"],
    kunyomi: ["あめ", "あま-"],
    jlpt: 5,
  },
  {
    char: "木",
    meaning: "Tree",
    onyomi: ["モク", "ボク"],
    kunyomi: ["き", "こ-"],
    jlpt: 5,
  },
  {
    char: "六",
    meaning: "ロク",
    onyomi: ["むっ.つ", "む.つ", "むい", "む"],
    kunyomi: [""],
    jlpt: 5,
  },
  {
    char: "万",
    meaning: "Ten thousand (10.000)",
    onyomi: ["マン", "バン"],
    kunyomi: [""],
    jlpt: 5,
  },
  {
    char: "白",
    meaning: "White",
    onyomi: ["ハク"],
    kunyomi: ["しろ.い", "しろ", "しら-"],
    jlpt: 5,
  },
  {
    char: "七",
    meaning: "Seven",
    onyomi: ["シチ"],
    kunyomi: ["なな.つ", "なな", "なの"],
    jlpt: 5,
  },
  {
    char: "円",
    meaning: "Circle, Yen",
    onyomi: ["エン"],
    kunyomi: ["まる.い"],
    jlpt: 5,
  },
  {
    char: "電",
    meaning: "Electricity",
    onyomi: ["デン"],
    kunyomi: [""],
    jlpt: 5,
  },
  {
    char: "父",
    meaning: "Father",
    onyomi: ["フ"],
    kunyomi: ["ちち"],
    jlpt: 5,
  },
  {
    char: "北",
    meaning: "North",
    onyomi: ["ホク"],
    kunyomi: ["きた"],
    jlpt: 5,
  },
  {
    char: "車",
    meaning: "Car",
    onyomi: ["シャ"],
    kunyomi: ["くるま"],
    jlpt: 5,
  },
  {
    char: "母",
    meaning: "Mother",
    onyomi: ["ボ"],
    kunyomi: ["はは"],
    jlpt: 5,
  },
  {
    char: "半",
    meaning: "Half",
    onyomi: ["ハン"],
    kunyomi: ["なか.ば"],
    jlpt: 5,
  },
  {
    char: "百",
    meaning: "Hundred (100)",
    onyomi: ["ヒャク"],
    kunyomi: [""],
    jlpt: 5,
  },
  {
    char: "土",
    meaning: "Ground, Earth",
    onyomi: ["ド", "ト"],
    kunyomi: ["つち"],
    jlpt: 5,
  },
  {
    char: "西",
    meaning: "West",
    onyomi: ["セイ", "サイ"],
    kunyomi: ["にし"],
    jlpt: 5,
  },
  {
    char: "読",
    meaning: "Read",
    onyomi: ["ドク", "トク", "トウ"],
    kunyomi: ["よ.む"],
    jlpt: 5,
  },
  {
    char: "千",
    meaning: "Thousand (1000)",
    onyomi: ["セン"],
    kunyomi: ["ち"],
    jlpt: 5,
  },
  {
    char: "校",
    meaning: "Exam",
    onyomi: ["コウ"],
    kunyomi: [""],
    jlpt: 5,
  },
  {
    char: "右",
    meaning: "Right",
    onyomi: ["ウ", "ユウ"],
    kunyomi: ["みぎ"],
    jlpt: 5,
  },
  {
    char: "南",
    meaning: "South",
    onyomi: ["ナン", "ナ"],
    kunyomi: ["みなみ"],
    jlpt: 5,
  },
  {
    char: "左",
    meaning: "Left",
    onyomi: ["サ"],
    kunyomi: ["ひだり"],
    jlpt: 5,
  },
  {
    char: "友",
    meaning: "Friend",
    onyomi: ["ユウ"],
    kunyomi: ["とも"],
    jlpt: 5,
  },
  {
    char: "火",
    meaning: "Fire",
    onyomi: ["カ"],
    kunyomi: ["ひ", "ほ-"],
    jlpt: 5,
  },
  {
    char: "毎",
    meaning: "Every, Each",
    onyomi: ["マイ"],
    kunyomi: [""],
    jlpt: 5,
  },
  {
    char: "雨",
    meaning: "ウ",
    onyomi: ["あめ"],
    kunyomi: ["あま-"],
    jlpt: 5,
  },
  {
    char: "休",
    meaning: "Rest",
    onyomi: ["キュウ"],
    kunyomi: ["やす.む", "やす.まる", "やす.める"],
    jlpt: 5,
  },
  {
    char: "午",
    meaning: "Noon",
    onyomi: ["ゴ"],
    kunyomi: [""],
    jlpt: 5,
  },
];
